name: Playwright Regression End-to-End Suite
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-cache: 'npm'
        node-version: lts/*
        
    - name: Install Project Dependencies
      run: npm ci
      
    - name: Install Playwright System & Browser Binaries
      run: npx playwright install --with-deps

    - name: Generate BDD Test Manifest and Run Suite
      run: npx bddgen && npx playwright test
      
    - name: Upload HTML Test Report on Failure
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30